version: 2.1
orbs:
  node: circleci/node@5.0.2
jobs:
  deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - run: npm run deploy

workflows:
  docs:
    jobs:
      - deploy
