get:
  tags:
    - Products
  summary: List products
  operationId: listProducts
  description: Receive list of products saved in the database.
  parameters:
  - in: query
    name: _sort
    required: false
    examples:
    - 'id'
    schema:
      type: string
      enum:
      - riskScore
      - createdAt
  - in: query
    name: _order
    description: Order of list (DESC or ASC) based on the sorting parameter.
    required: false
    schema:
      type: string
      enum:
      - DESC
      - ASC
  - in: query
    name: _start
    description: The start number of the products list.
    required: false
    examples:
    - '0'
    schema:
      type: number
  - in: query
    name: _end
    description: The end number of the products list.
    required: false
    examples:
    - '10'
    schema:
      type: number
  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "#/components/schemas/Product"
    400:
      description: Invalid parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidBody"
    500:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBody"
  security:
  - bearerAuth: []

post:
  tags:
  - Products
  summary: Create product
  operationId: createProduct
  description: Create a new product.
  requestBody:
    content:
      application/json:
        schema:
          $ref: "#/components/schemas/ProductBody"

  responses:
    200:
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Product"
    400:
      description: Invalid parameters
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/InvalidBody"
    500:
      description: Server Error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorBody"
  security:
  - bearerAuth: []
