type: object
properties:
  productInformation:
    type: object
    description: Information about the product
    properties:
      adress:
        type: object
        description: Address associated to the lineOfBusiness product
        properties: 
          streetAdress:
            type: string
            description: Street part of the address. Typically street name and house number
          postalCode:
            type: string
            description: Postal code
          city:
            type: string
            description: City
          country:
            type: string
            format: ISO 3166 ALPHA-3
            description: Country
            example: SWE
      email:
        type: string
        format: email
        description: Contact email associated to the lineOfBusiness product
        example: test@test.com
      phone:
        type: string
        description: Phone number associated to the lineOfBusiness product
        example: "0701234567"
