allOf:
- $ref: '#/components/schemas/ProductBodyBase'
- type: object
  properties:
    customIds:
      description: List of all unique customIds from different sources. Used to update the whole list.
      externalDocs:
        description: Unique identifier
        url: '/#section/Introduction/Unique-Identifier'
      type: array
      items:
        type: string
    addGroups:
      description: List of group IDs to add to the entity.
      type: array
      items:
        type: string
        format: ObjectId
    removeGroups:
      description: List of group IDs to remove from the entity.
      type: array
      items:
        type: string
        format: ObjectId
