type: object
properties:
  productInformation:
    type: object
    description: Information about the product
    properties:
      invoiceDate:
        type: string
        format: date
        description: Date when the invoice was issued
        example: "2023-10-01"
      dueDate:
        type: string
        format: date
        description: Date when the invoice is due
        example: "2023-10-30"
      currency:
        type: string
        description: Currency code in ISO 4217 format
        example: "USD"
      invoiceAmount:
        type: number
        description: Total amount of the invoice including VAT
        example: 1000.00
      vatAmount:
        type: number
        description: Amount of VAT included in the invoice
        example: 250.00
      invoiceNumber:
        type: string
        description: Unique identifier for the invoice
        example: "INV-1001"
      customerNumber:
        type: string
        description: Unique identifier for the customer as stated on the invoice
        example: "CUST-2002"
      issuer:
        type: object
        description: Information about the issuer of the invoice
        required:
          - type
          - id
        properties:
          type:
            type: string
            description: Entity type of the issuer
            enum:
              - Individual
              - Business
          id:
            type: string
            format: ObjectId
            description: Unique identifier of the issuer in the system
            example: "62b9437318fe4517089b2833"
      paymentDetails:
        type: object
        description: Payment details for the invoice
        properties:
          accountNumber:
            type: string
            description: Account number to which the payment should be made. Format depends on the method of payment.
            example: "1234567890"
          reference:
            type: string
            description: Payment reference to be used when making the payment
            example: "REF-3003"
          method:
            type: string
            description: Payment method to be used
            enum:
              - bank-transfer
              - swish
              - bankgiro
              - plusgiro
              - other
    required:
      - invoiceDate
      - dueDate
      - currency
      - invoiceAmount
required:
  - productInformation
